language: minimal

sudo: required

services:
  - docker

if: tag IS present

script:
  - docker build --tag $DOCKER_USERNAME/avitools --build-arg avi_version=${TRAVIS_BRANCH} .
  - docker run --rm $DOCKER_USERNAME/avitools terraform version
  - docker run --rm $DOCKER_USERNAME/avitools ansible --version
  - docker run --rm $DOCKER_USERNAME/avitools kubectl version --client
  - docker run --rm $DOCKER_USERNAME/avitools oc version
after_success:
  - docker tag timarenz/avitools timarenz/avitools:${TRAVIS_BRANCH}
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    script: docker push timarenz/avitools
    skip_cleanup: true
    on:
      tags: true
